name: Linter & Unittests & Deploy

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('app/requirements.txt') }}
      - run: pip install flake8
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  unittest:
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('app/requirements.txt') }}
      - run: pip install -r requirements.txt
      - run: python -m unittest discover -s . -p "unittests.py" -v


  deploy:
    needs: unittest
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('app/requirements.txt') }}
      - run: pip install -r requirements.txt
      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: '1.27.0' # Ensure you are using the correct version of kubectl for your needs
      - name: Load Kubernetes config
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
      - run: kubectl apply -f app-manifests.yaml
      - run: kubectl rollout status deployment/my-app -n my-namespace
